//this source code was auto-generated by tolua#, do not modify it
using System;
using LaoHan.Infrastruture.ulua;

public class LaoHan_Infrastruture_lhObjectManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LaoHan.Infrastruture.lhObjectManager), typeof(System.Object));
		L.RegFunction("GetInstance", GetInstance);
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("poolParent", get_poolParent, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			LaoHan.Infrastruture.lhObjectManager o = LaoHan.Infrastruture.lhObjectManager.GetInstance();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LaoHan.Infrastruture.lhObjectManager obj = (LaoHan.Infrastruture.lhObjectManager)ToLua.CheckObject(L, 1, typeof(LaoHan.Infrastruture.lhObjectManager));
			obj.Dispose();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_poolParent(IntPtr L)
	{
		ToLua.Push(L, LaoHan.Infrastruture.lhObjectManager.poolParent);
		return 1;
	}
}

