//this source code was auto-generated by tolua#, do not modify it
using System;
using LaoHan.Infrastruture.ulua;

public class UnityEngine_SleepTimeoutWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.SleepTimeout), typeof(System.Object));
		L.RegFunction("New", _CreateUnityEngine_SleepTimeoutWrap);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegConstant("NeverSleep", -1);
		L.RegConstant("SystemSetting", -2);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_SleepTimeoutWrap(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.SleepTimeout obj = new UnityEngine.SleepTimeout();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.SleepTimeout.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}
}

